theme = "ananke"
title = "surjsingh.github.io"
baseURL = "https://surjsingh.github.io"
languageCode = "en-gb"
disqusShortname = "https-surjsingh-github-io"

[author]
  name = "Surjeet Singh"
  homepage = "https://surjsingh.github.io/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
show_reading_time = true
background_color_class = "bg-black"
recent_posts_number = 2

